const factionList = [
  { value: 'AdM', label: 'Ad Mech', img: '/AdM.webp' },
  { value: 'AC', label: 'Adeptus Custodes', img: '/custodes.jpg' },
  { value: 'AE', label: 'Aeldari', img: '/AE.jpg' },
  { value: 'AM', label: 'Astra Militarum', img: '/AM.jpg' },
  { value: 'AS', label: 'Adepta Soroitas', img: '/sisters.jpg' },
  { value: 'AoI', label: 'Agents of the Imperium', img: '/AoI.jpg' },
  { value: 'CD', label: 'Chaos Daemons', img: '/CD.jpg' },
  { value: 'QT', label: 'Chaos Knights', img: '/QT.webp' },
  { value: 'CSM', label: 'Chaos Space Marines', img: '/CSM.jpg' },
  { value: 'DG', label: 'Death Guard', img: '/DG.jpg' },
  { value: 'DRU', label: 'Drukari', img: '/DRU.webp' },
  { value: 'GC', label: 'Genestealer Cults', img: '/gsc.jpg' },
  { value: 'GK', label: 'Grey Knights', img: '/GK.webp' },
  { value: 'QI', label: 'Imperial Knights', img: '/Imperial_Knights.webp' },
  { value: 'LoV', label: 'Leagues of Votaan', img: '/LoV.webp' },
  { value: 'NEC', label: 'Necrons', img: '/NEC.jpg' },
  { value: 'ORK', label: 'Orks', img: '/Orks.webp' },
  { value: 'SM', label: 'Space Marines', img: '/SpaceMarines.jpeg' },
  { value: 'TS', label: 'Thousand Sons', img: '/TSONS.png' },
  { value: 'TAU', label: 'Tau Empire', img: '/tau.jpg' },
  { value: 'TYR', label: 'Tyranids', img: '/TYR.jpg' },
  { value: 'WE', label: 'World Eaters', img: '/WE.jpg' },
  { value: 'EC', label: 'Emperors Children', img: '/EC.avif' },
];

export default factionList